dummy_antrian = [
    {"nama": "Pasien 1", "poli": "Umum", "keperluan": "Darurat"},
    {"nama": "Pasien 2", "poli": "Gigi", "keperluan": "Kontrol Rutin"},
    {"nama": "Pasien 3", "poli": "Mata", "keperluan": "Sakit Berat"},
    {"nama": "Pasien 4", "poli": "Anak", "keperluan": "Konsultasi"},
    {"nama": "Pasien 5", "poli": "Umum", "keperluan": "Darurat"},
    {"nama": "Pasien 6", "poli": "Gigi", "keperluan": "Konsultasi"},
    {"nama": "Pasien 7", "poli": "Mata", "keperluan": "Sakit Berat"},
    {"nama": "Pasien 8", "poli": "Anak", "keperluan": "Kontrol Rutin"},
    {"nama": "Pasien 9", "poli": "Umum", "keperluan": "Darurat"},
    {"nama": "Pasien 10", "poli": "Gigi", "keperluan": "Konsultasi"},
    {"nama": "Pasien 11", "poli": "Mata", "keperluan": "Darurat"},
    {"nama": "Pasien 12", "poli": "Anak", "keperluan": "Sakit Berat"},
    {"nama": "Pasien 13", "poli": "Umum", "keperluan": "Kontrol Rutin"},
    {"nama": "Pasien 14", "poli": "Gigi", "keperluan": "Darurat"},
    {"nama": "Pasien 15", "poli": "Mata", "keperluan": "Konsultasi"},
    {"nama": "Pasien 16", "poli": "Anak", "keperluan": "Darurat"},
    {"nama": "Pasien 17", "poli": "Umum", "keperluan": "Sakit Berat"},
    {"nama": "Pasien 18", "poli": "Gigi", "keperluan": "Kontrol Rutin"},
    {"nama": "Pasien 19", "poli": "Mata", "keperluan": "Darurat"},
    {"nama": "Pasien 20", "poli": "Anak", "keperluan": "Konsultasi"},
]